### PR TITLE
Add introductory section on transient execution attacks

### PR DESCRIPTION
**Pull request by kbeyls**
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121)

### CODE REVIEW

**Comment by kbeyls** [comment]
I'd like to try out Reviewable as an alternative code review tool than the one built in to github.
It promises to make complex reviews easier to do.
I think that the correct link to the review of the pull request in Reviewable is https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121.
For the reviewers: could you try out reviewing there?
If I understood the Reviewable documentation correctly, your comments in reviewable should also get posted here.

**Comment by JLouisKaplan-Arm** [comment]
Unfortunately I got this error after I finished my review on Reviewable and tried to publish it:

` Failed to publish: GitHub error 403 on POST https://api.github.com/repos/llsoftsec/llsoftsecbook/pulls/121/reviews: Although you appear to have the correct authorization credentials, the `llsoftsec` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/ `

**Comment by JLouisKaplan-Arm** [comment]
Happy to publish my review directly here for now if you'd prefer?

**Review by JLouisKaplan-Arm — CHANGES_REQUESTED** [review]
Very clear and interesting - I learnt a lot. Thanks Kristof.

I'm still working out exactly how the Reviewable UI works but, as always, please take my comments as merely suggestions.

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-:-NI-7jMkAAgFNgRm2Sur:b5sp4z1)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @g-kouv and @kbeyls)

___
*[`book.md` line 1432 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzeSWg7qzy3wzBA3MA:-NHzeSWg7qzy3wzBA3MB:b45qaf5) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1432)):*
> ```Markdown
> time, all in various stages of execution. In other words, instructions start
> executing while potentially hundreds of previous instructions haven't produced
> their results yet. How can a CPU do so when the input to an instruction is so
> ```

stylistic suggestion: "How can a CPU _achieve this_..."
___
*[`book.md` line 1434 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzeZbW2LK0Y2SLU1Ch:-NHzeZbW2LK0Y2SLU1Ci:bppq437) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1434)):*
> ```Markdown
> their results yet. How can a CPU do so when the input to an instruction is so
> often the output of a previous instruction, which might not have fully executed
> yet, and hence the output not being ready?
> ```

stylistic suggestion: "and hence whose output is may not yet be ready"
or consider removing this last bit after the comma as I think it's implicit.
___
*[`book.md` line 1436 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzekKa7MW-cIDOtQjE:-NHzekKa7MW-cIDOtQjF:b-z2580x) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1436)):*
> ```Markdown
> yet, and hence the output not being ready?
> 
> The answer is the CPUs making massive numbers of *predictions*\index{prediction}
> ```

stylistic suggestion: "The answer is that CPUs make..."
slight change in tense to simple present
___
*[`book.md` line 1482 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzgFQeEyL3ZFOJrMYk:-NHzgFQeEyL3ZFOJrMYl:b-f19zfk) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1482)):*
> ```Markdown
> 
> \todo{Should I show a second example of cpu speculation that is not based on
> branch prediction?}
> ```

side note: I would find this [todo] useful!
___
*[`book.md` line 1485 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-3qFv60TgpqBahCBq:-NI-3qFv60TgpqBahCBr:b-nz5arq) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1485)):*
> ```Markdown
> 
> Of course, as with all predictions, the CPU gets the prediction wrong from time
> to time. In that case, all changes to the system state that affects the correct
> ```

grammar suggestion: affects -> affect
___
*[`book.md` line 1486 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-4GhA63EKsLxCkPB5:-NI-4GhA63EKsLxCkPB6:br3uibu) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1486)):*
> ```Markdown
> Of course, as with all predictions, the CPU gets the prediction wrong from time
> to time. In that case, all changes to the system state that affects the correct
> execution of the program, needs to be undone. For example, in the above example
> ```

grammar suggestion: needs -> need
stylistic suggestion: could remove the comma before need
___
*[`book.md` line 1489 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-4i0m7gzR9y8iG5_O:-NI-4i0nCHMTqD1wYqXh:b-3vuygy) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1489)):*
> ```Markdown
> if the branch should have been taken, but the CPU predicted it would not be
> taken, the `neg` instruction would be executed incorrectly and change the value
> in register x0. After discovering the branch was mis-predicted, the CPU would
> ```

stylistic: I struggle to visualise if this idea makes sense - but do you think it might make sense to format in-text register names with backticks? (I.e. format `x0` in the same way you have `neg` above, for example.)

**Review by kbeyls — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-:-NI2fqFH6Q_Nz6Et31rp:bnfp4nl)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @g-kouv and @JLouisKaplan-Arm)

___
*[`book.md` line 1432 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzeSWg7qzy3wzBA3MA:-NI2dawH-oVEtCoH7kfa:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1432)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

stylistic suggestion: "How can a CPU _achieve this_..."
</blockquote></details>

Done.
___
*[`book.md` line 1434 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzeZbW2LK0Y2SLU1Ch:-NI2dppG-UGV5IXz6hm8:b-gjtbjr) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1434)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

stylistic suggestion: "and hence whose output is may not yet be ready"
or consider removing this last bit after the comma as I think it's implicit.
</blockquote></details>

Thanks. I think I'll keep the part after the comma (adapted to you suggested improved wording). My reason for keeping it is that transient execution may be hard to understand, so I thought it's useful to be more explicit in the explanation of it. If there would be many implicit parts, just missing one of the implicit parts might make it a lot harder to understand the concept?
___
*[`book.md` line 1436 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzekKa7MW-cIDOtQjE:-NI2eRac2cXfU05nfvLz:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1436)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

stylistic suggestion: "The answer is that CPUs make..."
slight change in tense to simple present
</blockquote></details>

Done.
___
*[`book.md` line 1482 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NHzgFQeEyL3ZFOJrMYk:-NI2eZaoAZS8kWTT1G40:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1482)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

side note: I would find this [todo] useful!
</blockquote></details>

Done.
___
*[`book.md` line 1485 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-3qFv60TgpqBahCBq:-NI2ed-_BZ1K3KWkf735:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1485)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

grammar suggestion: affects -> affect
</blockquote></details>

Done.
___
*[`book.md` line 1486 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-4GhA63EKsLxCkPB5:-NI2ehwj0mgWJtk4PKZC:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1486)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

grammar suggestion: needs -> need
stylistic suggestion: could remove the comma before need
</blockquote></details>

Done.
___
*[`book.md` line 1489 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-4i0m7gzR9y8iG5_O:-NI2erp_5A0SyFtRb0Bf:b-9sg6lx) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1489)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

stylistic: I struggle to visualise if this idea makes sense - but do you think it might make sense to format in-text register names with backticks? (I.e. format `x0` in the same way you have `neg` above, for example.)
</blockquote></details>

That makes sense. I've followed your suggestion.

**Review by g-kouv — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121)* status: all files reviewed, 10 unresolved discussions (waiting on @JLouisKaplan-Arm and @kbeyls)

___
*[`book.md` line 1426 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI2jY6d3lwhvzEqG6Dy:-NI2jY6d3lwhvzEqG6Dz:bd2ayb1) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/33b0630d9171dd1008ce7d1a3ee3d532e22cea1b/book.md#L1426)):*
> ```Markdown
> CPUs execute sequences of instructions. There often are dependencies between
> instructions in the sequence. That means that the output of one instruction is
> often input to a later instruction.
> ```

This is only one type of data dependency, is it worth going into true, output and anti- dependencies, and maybe even control dependencies (which are very relevant for speculation)?
___
*[`book.md` line 1438 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI2kjjnBLP_L1AjCKcq:-NI2kjjnBLP_L1AjCKcr:b-3fhabd) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/33b0630d9171dd1008ce7d1a3ee3d532e22cea1b/book.md#L1438)):*
> ```Markdown
> The answer is that CPUs make massive numbers of *predictions*\index{prediction}
> on what the outputs are likely to be before they are available. Based on those
> predictions, later instructions start executing with a predicted value. This is
> ```

This sounds like value prediction, rather than speculative execution in general. Perhaps you could start with a focus on branch prediction, which is more common and demonstrated in the example, and mention value prediction later? Changing "output" and "value" to "outcome" would be good to make this generic rather than specific to any type of prediction.
___
*[`book.md` line 1490 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI2m7OF42qbktKE3sfY:-NI2m7OF42qbktKE3sfZ:b1y0wh7) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/33b0630d9171dd1008ce7d1a3ee3d532e22cea1b/book.md#L1490)):*
> ```Markdown
> taken, the `neg` instruction would be executed incorrectly and change the value
> in register `x0`. After discovering the branch was mis-predicted, the CPU would
> have to restore the correct, non-negated, value in register x0.
> ```

I think that it would be more realistic to explain that changes to the state do not become visible until the prediction is validated, rather than first done and later undone if a prediction was found to be wrong.

**Review by kbeyls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @g-kouv and @JLouisKaplan-Arm)

___
*[`book.md` line 1489 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NI-4i0m7gzR9y8iG5_O:-NI6jt_vD_K5tb6myHPt:b-4afw8s) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/cb8c088733f45d33e81d0cd55a62913a406045b5/book.md#L1489)):*
<details><summary><i>Previously, JLouisKaplan-Arm (Jonathan Louis Kaplan) wrote…</i></summary><blockquote>

Sounds good to me. Leaving this one open just as a reminder there are 1 or 2 other instances of in-text x0 that could be updated to be consistent with the change
</blockquote></details>

Ah yes, there are more occurrences of x0 in this patch. I hope I marked them all as code (i.e. surrounding them with backticks) now.

**Review by g-kouv — APPROVED** [review]
LGTM, thanks!

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-:-NICFREx-HLKbgqjEROs:b2c0zcb)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @JLouisKaplan-Arm and @kbeyls)

___
*[`book.md` line 1534 at r4](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121#-NICEyZTC2flGf4MMbYu:-NICEyZUB7RjbaosGVvg:b-disk5a) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/9145898654c488aa2a52bfb85ea79b32c584f9c1/book.md#L1534)):*
> ```Markdown
> The above explanation describes architectural effects as changes in system state
> that need to be undone after detecting mis-speculation. In reality, most systems
> will implement techniques such that it keeps all state changes in
> ```

Nit: "techniques such that it keeps" -> "techniques that/to keep"

**Review by JLouisKaplan-Arm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @g-kouv and @kbeyls)

**Review by kbeyls — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/121)* status: all files reviewed, 3 unresolved discussions (waiting on @g-kouv)

**Pull request merged**
