### PR TITLE
Add paragraph on ROP gadgets and variable length instructions

### PR DESCRIPTION
**Pull request by wanders**
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245)

### CODE REVIEW

**Review by kbeyls — COMMENTED** [review]
Thank you!
This looks good, just have left a few nit picks.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-:-NxGsI9N1tBsw55Q6FTc:b-ejpe2b)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`book.md` line 630 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxGrbmYE33q4kxY8q-T:-NxGrbmYE33q4kxY8q-U:basmg5t) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L630)):*
> ```Markdown
> that should be protected and have been missed.
> 
> On architectures such as x86 that has variable length instruction encoding
> ```

s/has/have/
___
*[`book.md` line 631 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxGrewj7_yeHqV_eBH-:-NxGrewj7_yeHqV_eBH0:b-6nzf19) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L631)):*
> ```Markdown
> 
> On architectures such as x86 that has variable length instruction encoding
> where instructions doesn't have any alignment requirements there will also
> ```

s/doesn't/do not/
___
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxGrlbz7wgiJm_-0LBg:-NxGrlbz7wgiJm_-0LBh:b-8u9j1d) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
> ```Markdown
> On architectures such as x86 that has variable length instruction encoding
> where instructions doesn't have any alignment requirements there will also
> exist gadgets that the compiler has not emitted as instructions. For example,
> ```

maybe s/exist/be/? But this is a matter of taste, so if you prefer "exist", let's keep "exist".

**Comment by wanders** [comment]
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxGrlbz7wgiJm_-0LBg:-NxH1bBL2pLx4QVry5MY:bv9vf7c) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
I think I prefer "be".  But maybe even

> On architectures such as x86 that has variable length instruction encoding
> where instructions doesn't have any alignment requirements it is possible
> to find gadgets that the compiler has not emitted as instructions.

**Review by kbeyls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxGrlbz7wgiJm_-0LBg:-NxH5rPP03gl9X_-qdj5:by3kqvx) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
<details><summary><i>Previously, wanders (Anders Waldenborg) wrote…</i></summary><blockquote>

I think I prefer "be".  But maybe even

> On architectures such as x86 that has variable length instruction encoding
> where instructions doesn't have any alignment requirements it is possible
> to find gadgets that the compiler has not emitted as instructions.
</blockquote></details>

Oh yes, that's better!

**Review by g-kouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kbeyls and @wanders)

___
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxI8wcZ29XKKA8wh_t1:-NxI8wc_1ORUJwnPYnYv:bxfc8ir) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
> ```Markdown
> On architectures such as x86 that has variable length instruction encoding
> where instructions doesn't have any alignment requirements there will also
> exist gadgets that the compiler has not emitted as instructions. For example,
> ```

If we're mentioning variable-length instructions, it might also be worth mentioning that this can also happen in other cases, e.g. literal pools embedded in the code, read-only data that gets mapped in the same segment as code etc. This kind of thing is particularly interesting in JITs when the input code (and therefore these values) is attacker controlled.

**Comment by wanders** [comment]
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxI8wcZ29XKKA8wh_t1:-NxIF4GQ1wYDWLk6CyAG:b-44hp3p) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
<details><summary><i>Previously, g-kouv (Georgia Kouveli) wrote…</i></summary><blockquote>

If we're mentioning variable-length instructions, it might also be worth mentioning that this can also happen in other cases, e.g. literal pools embedded in the code, read-only data that gets mapped in the same segment as code etc. This kind of thing is particularly interesting in JITs when the input code (and therefore these values) is attacker controlled.
</blockquote></details>

Good point. I'll see if I can cover that too.

**Review by kbeyls — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @g-kouv)

___
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxI8wcZ29XKKA8wh_t1:-NxM5MkRDfwpEzk4nKBS:b-zcv0vb) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
<details><summary><i>Previously, wanders (Anders Waldenborg) wrote…</i></summary><blockquote>

Good point. I'll see if I can cover that too.
</blockquote></details>

I like the text, it reads well and explains the idea well.
Georgia, what do you think?
___
*[`book.md` line 649 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxM5Bts-p1HJnQLL-YG:-NxM5Bts-p1HJnQLL-YH:bgg16i4) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/4b635b4b8927dbb66d64ef04b7f24a6edde8c5d6/book.md#L649)):*
> ```Markdown
> `66 b8 5f c3`. If the attacker can divert execution two bytes into that 4-byte
> instruction it will execute `5f c3`. Those bytes corresponds to the two single
> byte instructions `pop %rdi; ret` which is an useful ROP gadget.
> ```

s/an useful/a useful/?

**Review by kbeyls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @g-kouv)

___
*[`book.md` line 632 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245#-NxI8wcZ29XKKA8wh_t1:-NxrGOmU8ry8casm6PRG:b-prgco5) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e53528ae566507f49e343a9b3ab4e6e090cbcffd/book.md#L632)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I like the text, it reads well and explains the idea well.
Georgia, what do you think?
</blockquote></details>

Georgia may not be available to do another review in the near future.
Let's land this improvement to the text.
We can always adapt it further in the future.

**Pull request merged**
