### PR TITLE
[HTML] Add github repo and edit buttons.

### PR DESCRIPTION
**Pull request by kbeyls**
This adds 2 buttons in the top row:
* One button to go to the llsoftsecbook github repository.
* One button to open the github page that enables to edit the book text and immediately create a commit/pull request in the browser.

- - -
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137)

### CODE REVIEW

**Review by kbeyls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137#-:-NMEnBeaAKmR4GBvnXhr:b-unpev8)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @g-kouv and @JLouisKaplan-Arm)

**Review by JLouisKaplan-Arm — APPROVED** [review]
lgtm!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137#-:-NMEpEAA-jx3qC7XibKD:b-7nbn20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @g-kouv)

**Review by g-kouv — APPROVED** [review]
Very nice!

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137#-:-NMEr3661k4rreyfyRPX:b-j7qk9t)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @JLouisKaplan-Arm)

**Review by kbeyls — COMMENTED** [review]
Thanks for the quick review @JLouisKaplan-Arm !

The follow-on commit also adds tooltips, see screenshot below:



> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137#-:-NMEqvRwBgEGtTRGjhOG:bvc884b)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @JLouisKaplan-Arm)

**Review by JLouisKaplan-Arm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
