### PR TITLE
Add section on bounds checking

### PR DESCRIPTION
**Pull request by g-kouv**
...also fix missing punctuation in an earlier section

- - -
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209)

### CODE REVIEW

**Review by kbeyls — CHANGES_REQUESTED** [review]
Thank you!

I mostly have a few very minor stylistic comments.
The one non-stylistic comment: I was thinking that maybe it would also be useful to have a paragraph on CHERI/Morello in this section?

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-:-NZBWMTwD-1824Hxnfz2:b-pj9hw3)* status: 0 of 2 files reviewed, 20 unresolved discussions (waiting on @g-kouv)

___
*[`book.md` line 1226 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBWcSa8cvqqvOyMP4V:-NZBWcSa8cvqqvOyMP4W:b-ggg9ud) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1226)):*
> ```Markdown
> 
> Making sure that memory accesses happen within the bounds of each object's
> allocation is a very important part of memory safety, usually described
> ```

Maybe split the sentence after "memory safety,"?
___
*[`book.md` line 1228 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBWirjC78JfwModMpJ:-NZBWirjC78JfwModMpK:b8daew2) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1228)):*
> ```Markdown
> allocation is a very important part of memory safety, usually described
> with the term "spatial memory safety"\index{spatial memory safety}.
> Out-of-bounds accesses result in partial read/write primitives, which an
> ```

Maybe split the sentence after "read/write primitives",?
___
*[`book.md` line 1228 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBX4UlEPu-hCuhWbGX:-NZBX4UlEPu-hCuhWbGY:b-jvas9a) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1228)):*
> ```Markdown
> allocation is a very important part of memory safety, usually described
> with the term "spatial memory safety"\index{spatial memory safety}.
> Out-of-bounds accesses result in partial read/write primitives, which an
> ```

I was wondering in which way the read/write primitive is "partial". Would it make sense to add one or a few sentences to describe exactly how the read/write primitive is "partial"?
___
*[`book.md` line 1229 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBWpi19P7D8jKSwWLT:-NZBWpi19P7D8jKSwWLU:b8dam2e) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1229)):*
> ```Markdown
> with the term "spatial memory safety"\index{spatial memory safety}.
> Out-of-bounds accesses result in partial read/write primitives, which an
> attacker can often easily convert into arbitrary read/write primitives,
> ```

Maybe split the sentence after "read/write primitives,"?
___
*[`book.md` line 1229 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBWvvm-sy9saNGF6k0:-NZBWvvm-sy9saNGF6k1:b-xz4czl) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1229)):*
> ```Markdown
> with the term "spatial memory safety"\index{spatial memory safety}.
> Out-of-bounds accesses result in partial read/write primitives, which an
> attacker can often easily convert into arbitrary read/write primitives,
> ```

Given read/write primitives is mentioned a few times here, I was wondering whether it would make sense to add an \index{read/write primitive}?
___
*[`book.md` line 1234 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXHMU5-27hgOf3K4P:-NZBXHMU5-27hgOf3K4Q:b8c5rwc) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1234)):*
> ```Markdown
> 
> The C and C++ memory languages do not, as a general rule, perform bounds
> checking [^stdarray], which is one of the sources of memory errors in
> ```

Maybe split the sentence after "checking,"?
___
*[`book.md` line 1236 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXKVjBUZ6aOZ-PPwU:-NZBXKVk04-O4z_o5TdX:bouj16n) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1236)):*
> ```Markdown
> checking [^stdarray], which is one of the sources of memory errors in
> C/C++ programs. However, compilers have a history of introducing bounds
> checks, even though the language does not require them, in various scenarios,
> ```

Maybe split the sentence after "require them,"?
___
*[`book.md` line 1244 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXNWS3Sr-QWeEmGa4:-NZBXNWS3Sr-QWeEmGa5:b-ukbve8) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1244)):*
> ```Markdown
> 
> One of the simplest compiler options is `-Warray-bounds`, which warns
> when an array access is always out of bounds, which restricts it to
> ```

Maybe split the sentence after "out of bounds,"?
___
*[`book.md` line 1249 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXRUg2ueoQhcpk-F_:-NZBXRUg2ueoQhcpk-Fa:b9642fu) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1249)):*
> ```Markdown
> 
> Another option supported by both compilers is `-fsanitize=bounds`, which is a
> part of [UBSan](#sanitizers), described in the previous section, meant to check
> ```

Maybe split the sentence after "previous section,"?
___
*[`book.md` line 1250 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXVhXANn2_AoM2FJD:-NZBXVhXANn2_AoM2FJE:b-cizf6) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1250)):*
> ```Markdown
> Another option supported by both compilers is `-fsanitize=bounds`, which is a
> part of [UBSan](#sanitizers), described in the previous section, meant to check
> the bounds for accesses to statically sized arrays.  This is an improvement
> ```

Maybe s/This is an improvement/This improves/?
___
*[`book.md` line 1253 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXdGp5eIdeUpap3qt:-NZBXdGq4Hys5FmtMe09:bv70ibb) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1253)):*
> ```Markdown
> over `-Warray-bounds`, as it can also check accesses to dynamic indices.
> However, it's still limited, as it cannot perform bounds checks on dynamically
> sized arrays, and it is still restricted to array bounds checking.
> ```

"still restricted to array bounds checking" -> This made me wonder which other data types can have out-of-bound accesses, and hence could use bounds checking? Would it be useful to explicitly enumerate a number of other data types that can use bounds checking?
I could only think of strings of the top of my head, and even there, that could be seen as a special kind of array?
___
*[`book.md` line 1258 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBY5l80kfnvUxjcZVn:-NZBY5l80kfnvUxjcZVo:b-9ogsf9) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1258)):*
> ```Markdown
> introduced by `-fsanitize=bounds` and the Address Sanitizer. Although the scope
> of `-fsanitize=bounds` is restricted to statically sized arrays, it's
> interesting to note that it can still catch intra-object overflows on array
> ```

I think "intra-object overflow" is an important term.
Maybe even important enough to have a table at some future point in the book that lists the mitigations described and have a check box if they can mitigate against intra-object overflow?
Of course other columns in the table could be "inter-object overflow", "temporal memory vulnerability", "type confusion", etc.?
For this patch, I was thinking that maybe just adding "intra-object overflow" to the index suffices?
___
*[`book.md` line 1301 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBYhd84LpiSDbL7bep:-NZBYhd84LpiSDbL7beq:b32czi3) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1301)):*
> ```Markdown
> annotation burden placed on programmers by only requiring the annotations at
> [ABI](https://en.wikipedia.org/wiki/Application_binary_interface)\index{Application
> binary interface (ABI)} boundaries. Local variables, which do not cross ABI
> ```

This triggers the question with me: how to define what an "ABI boundary" is. Would there be a short description that we could add to the book here (maybe in a footnote)? If not, is there a link that we can add to an external definition?
___
*[`book.md` line 1302 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBZ5AG8nlkR8mBkX5e:-NZBZ5AG8nlkR8mBkX5f:b-aicvdf) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1302)):*
> ```Markdown
> [ABI](https://en.wikipedia.org/wiki/Application_binary_interface)\index{Application
> binary interface (ABI)} boundaries. Local variables, which do not cross ABI
> boundaries, are implicitly converted to use wide pointers, which store bounds
> ```

I think it would be useful to split this sentence in 2. While trying to do so, I ended up writing the following 2 sentences on my side:
"
Pointer variables which do not
cross ABI boundaries are
automatically converted to
wide pointers. These wide pointers
store bounds information alongside
the original pointer.
"
___
*[`book.md` line 1311 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBZOq27wMuSKsux4UE:-NZBZOq38gleZFG4EXWA:b-ojmyzb) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1311)):*
> ```Markdown
> library. The [C++ Buffer Hardening
> proposal](https://discourse.llvm.org/t/rfc-c-buffer-hardening/65734) aims to
> extend this library hardening. The proposal will also see pointer arithmetic
> ```

I had to read this last sentence more than once to understand it well.
I tried to write up how I understood it as follows. Would such a text be easier to understand?
"
The proposal replaces pointer arithmetic that is considered
unsafe (footnote as per an analysis implemented in clang, with pointer?)
with safer alternatives that are implemented as run-time helper functions
in libc++. These safer alternatives do add bounds checks.
"
___
*[`book.md` line 1315 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBZc0K9tCWes9w7q8g:-NZBZc0K9tCWes9w7q8h:b-5mj5gw) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1315)):*
> ```Markdown
> library that will include bounds checks.
> 
> It's important note that successfully using compiler features like the ones
> ```

I thought this sentence could be made shorter by rephrasing it as follows:
"
Successfully using bounds checking compiler features for a large code base requires substantial effort.
As a good case study, [Kees Cook's blog]....
"
?
___
*[`book.md` line 1320 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZB_BxF3whwSPKuDcxW:-NZB_BxF3whwSPKuDcxX:bermu5j) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1320)):*
> ```Markdown
> in refactoring the Linux kernel to use bounds checks for flexible arrays.
> 
> This section would, of course, be incomplete without a mention of a different
> ```

I think this sentence could be made shorter and clearer by simply saying
"
Of course, an alternative way to mitigate against spatial memory vulnerabilities is using a language that has been designed with spatial memory safety in mind. Such languages make sure that all memory accesses are bounds checked, either at compile-time or runtime.
"
___
*[`book.md` line 1324 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZB_uP39gmSDX9ltO0R:-NZB_uP39gmSDX9ltO0S:b-j7omy9) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1324)):*
> ```Markdown
> with memory safety in mind, that can make sure all memory accesses are
> checked, either at compile-time or runtime. For example, the [Rust programming
> language](https://www.rust-lang.org/), a strongly typed compiled language,
> ```

When I read this, I thought that ", a strongly typed compiled language" was not needed in this sentence, and could be removed.
___
*[`book.md` line 1326 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBa23F3f4h0NIcuBNR:-NZBa23F3f4h0NIcuBNS:b6s82gk) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1326)):*
> ```Markdown
> language](https://www.rust-lang.org/), a strongly typed compiled language,
> introduces bounds checks whenever the compiler cannot prove that an access is
> within bounds (among other features that provide temporal memory safety and
> ```

Maybe split the sentence after "within bounds"?
___
*[`book.md` line 1328 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBa7MuDNW6tV0-e6Uy:-NZBa7MuDNW6tV0-e6Uz:bix727z) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1328)):*
> ```Markdown
> within bounds (among other features that provide temporal memory safety and
> thread-safety). There are many other memory safe languages, with different
> characteristics, for example JavaScript, a dynamically typed, usually
> ```

Maybe split the sentence after "with different characteristics,"?

**Review by g-kouv — COMMENTED** [review]
Adding a paragraph.

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-:-NZBr1Sm-kO5akDEILaY:b-j7opdz)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @kbeyls)

___
*[`book.md` line 1228 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBX4UlEPu-hCuhWbGX:-NZBgg4j-i03-_xGpFOr:b-7ksimg) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1228)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I was wondering in which way the read/write primitive is "partial". Would it make sense to add one or a few sentences to describe exactly how the read/write primitive is "partial"?
</blockquote></details>

Changed this to "restricted" which seems more natural, but also added a footnote.
___
*[`book.md` line 1236 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXKVjBUZ6aOZ-PPwU:-NZBcHeQ6J0zeDvVLbor:b-w4eqsf) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1236)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe split the sentence after "require them,"?
</blockquote></details>

I don't think that the sentence has the same meaning if split here, as it makes it sound like the compiler is doing something "bad" or unnecessary. I'll shorten the sentence by removing some other unnecessary bits.
___
*[`book.md` line 1249 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXRUg2ueoQhcpk-F_:-NZBd4OhEdkbaAPy1-NL:b7u8fs6) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1249)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe split the sentence after "previous section,"?
</blockquote></details>

Again, the sentence gets awkward if split as only "described in the previous section" is secondary. I'll shorten it by removing that part instead, the link to the previous section should make it obvious that it's described elsewhere.
___
*[`book.md` line 1250 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXVhXANn2_AoM2FJD:-NZBdbSl9iN8FxHFtVsc:bp3qcow) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1250)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe s/This is an improvement/This improves/?
</blockquote></details>

Actually, neither is accurate, as someone could argue that the additional runtime overhead makes `-fsanitize=bounds`"worse". I'll rephrase to "handles more cases than", which is what I meant.
___
*[`book.md` line 1253 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBXdGp5eIdeUpap3qt:-NZBfDGU7cgsTXYqdHzQ:b-e2clo9) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1253)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

"still restricted to array bounds checking" -> This made me wonder which other data types can have out-of-bound accesses, and hence could use bounds checking? Would it be useful to explicitly enumerate a number of other data types that can use bounds checking?
I could only think of strings of the top of my head, and even there, that could be seen as a special kind of array?
</blockquote></details>

Any access based on a pointer could be bounds-checked. Especially if involving pointer arithmetic. I'll elaborate!
___
*[`book.md` line 1258 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBY5l80kfnvUxjcZVn:-NZBj-iqCrXRjmfdBnux:b-s3r0ns) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1258)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I think "intra-object overflow" is an important term.
Maybe even important enough to have a table at some future point in the book that lists the mitigations described and have a check box if they can mitigate against intra-object overflow?
Of course other columns in the table could be "inter-object overflow", "temporal memory vulnerability", "type confusion", etc.?
For this patch, I was thinking that maybe just adding "intra-object overflow" to the index suffices?
</blockquote></details>

Agreed, a table would be nice once we cover enough mitigations/solutions. Adding to the index for noq.
___
*[`book.md` line 1301 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBYhd84LpiSDbL7bep:-NZBluNv6G4x6dhbd-0g:b-97v2ai) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1301)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

This triggers the question with me: how to define what an "ABI boundary" is. Would there be a short description that we could add to the book here (maybe in a footnote)? If not, is there a link that we can add to an external definition?
</blockquote></details>

I'm adding a footnote.
___
*[`book.md` line 1302 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBZ5AG8nlkR8mBkX5e:-NZBmWsGCi2r2Bj9IApD:b-23mj57) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1302)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I think it would be useful to split this sentence in 2. While trying to do so, I ended up writing the following 2 sentences on my side:
"
Pointer variables which do not
cross ABI boundaries are
automatically converted to
wide pointers. These wide pointers
store bounds information alongside
the original pointer.
"
</blockquote></details>

Rephrased splightly but still split into two. (I don't think "pointer variables" is accurate, as it doesn't include arrays, for example, even though ultimately they will be represented as pointers, so I kept "local variables" as used in the proposal).
___
*[`book.md` line 1311 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBZOq27wMuSKsux4UE:-NZBqTEX8wPE0h3Abghs:b9dfuu3) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1311)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I had to read this last sentence more than once to understand it well.
I tried to write up how I understood it as follows. Would such a text be easier to understand?
"
The proposal replaces pointer arithmetic that is considered
unsafe (footnote as per an analysis implemented in clang, with pointer?)
with safer alternatives that are implemented as run-time helper functions
in libc++. These safer alternatives do add bounds checks.
"
</blockquote></details>

Rephrased.
___
*[`book.md` line 1315 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBZc0K9tCWes9w7q8g:-NZBno0M-WYCuuR1mvLy:bqhm7mr) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1315)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I thought this sentence could be made shorter by rephrasing it as follows:
"
Successfully using bounds checking compiler features for a large code base requires substantial effort.
As a good case study, [Kees Cook's blog]....
"
?
</blockquote></details>

Rephrased even further.
___
*[`book.md` line 1320 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZB_BxF3whwSPKuDcxW:-NZBoXS89q4fWsOWnrxQ:b9dfuu3) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1320)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I think this sentence could be made shorter and clearer by simply saying
"
Of course, an alternative way to mitigate against spatial memory vulnerabilities is using a language that has been designed with spatial memory safety in mind. Such languages make sure that all memory accesses are bounds checked, either at compile-time or runtime.
"
</blockquote></details>

Rephrased.
___
*[`book.md` line 1324 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZB_uP39gmSDX9ltO0R:-NZBhaKh1Uj4LmY_Xu48:bcv32eb) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1324)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

When I read this, I thought that ", a strongly typed compiled language" was not needed in this sentence, and could be removed.
</blockquote></details>

I added this to make it clearer that it could be used for the same kinds of programs as C/C++, without attempting to claim it's a replacement. I suppose suggesting it as an alternative is clear enough already.
___
*[`book.md` line 1326 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZBa23F3f4h0NIcuBNR:-NZBiFhN0SwR6aI3_7t6:bq7c63o) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/6e28501495e7277d6a5f35fa45867ca9b47f26de/book.md#L1326)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe split the sentence after "within bounds"?
</blockquote></details>

The rest of the sentence is now demoted to a footnote. :) We could later consider a whole section on Rust, since it includes many interesting features from a compiler perspective.

**Review by kbeyls — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209)* status: all files reviewed, 2 unresolved discussions (waiting on @g-kouv)

___
*[`book.md` line 1234 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZQ6jAR-EhU2uFSoVqD:-NZQ6jAR-EhU2uFSoVqE:b-4cs0j2) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/250737013760f6be149bad02602cbe552b267e18/book.md#L1234)):*
> ```Markdown
> was the target of the problematic memory access.
> 
> [^restricted]: These primitives are restricted since they can access a
> ```

Maybe "they can only access"?
___
*[`book.md` line 1342 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZQ880m0buAAARTL_in:-NZQ880m0buAAARTL_io:b-bz33wi) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/250737013760f6be149bad02602cbe552b267e18/book.md#L1342)):*
> ```Markdown
> corresponding bounds and permissions. Capabilities cannot be forged, and can
> thus provide very strong guarantees. Arm has developed a prototype architecture
> that adapts CHERI, as well as prototype SoC and development board, as part of
> ```

maybe "as a prototype SoC"?

**Review by kbeyls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209)* status: all files reviewed, 2 unresolved discussions (waiting on @g-kouv)

**Review by g-kouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @g-kouv)

___
*[`book.md` line 1234 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZQ6jAR-EhU2uFSoVqD:-NZQBuoQ9NDQr8RYNUiF:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/250737013760f6be149bad02602cbe552b267e18/book.md#L1234)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe "they can only access"?
</blockquote></details>

Done.
___
*[`book.md` line 1342 at r2](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209#-NZQ880m0buAAARTL_in:-NZQC8hl5GBVg6qxhYt4:b-teuhl5) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/250737013760f6be149bad02602cbe552b267e18/book.md#L1342)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

maybe "as a prototype SoC"?
</blockquote></details>

Yeah :)

**Review by kbeyls — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @g-kouv)

**Pull request merged**
