### PR TITLE
Add chapter about compiler introduced security vulns

### PR DESCRIPTION
**Pull request by lucic71**
This is the draft I was discussing with @kbeyls in #183.

One thing that I was thinking about is if this should be a separate chapter or it should be somehow integrated with the chapter about supply chain attacks. Any ideas?

This is far from perfect so any feedback is welcomed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200)

### CODE REVIEW

**Review by g-kouv — CHANGES_REQUESTED** [review]
Hi Lucian! Thanks so much for this contribution! I've taken a first look and it looks very good! I've left some minor comments/suggestions, mostly about formatting fixes. (If you're having trouble building the book locally, you can also see the generated pdf and html in the automated checks' artifacts, for example here: https://github.com/llsoftsec/llsoftsecbook/actions/runs/5021453384?pr=200).

I'm happy with this being a separate chapter for the time being. I think there is also some common ground with the memory vulnerabilities chapter, but we can always reorganise the chapters later. The content you are adding is very useful and I'd rather see it committed sooner rather than later. :) Let's wait to see what Kristof thinks too!

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-:-NVosTjvBngawrJL5r3a:b87g35b)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @lucic71)

___
*[`book.md` line 1973 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVoZTZeBBFIYsgCAcgb:-NVoZTZeBBFIYsgCAcgc:b2hk784) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1973)):*
> ```Markdown
> vulnerabilities are added in the generated binary by the compiler.
> 
> When discussing about compiler introduced security vulnerabilities,
> ```

Nit: discussing about -> discussing.
___
*[`book.md` line 1975 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVoj9VB27WeiklDosLN:-NVoj9VB27WeiklDosLO:b-ou1bkn) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1975)):*
> ```Markdown
> When discussing about compiler introduced security vulnerabilities,
> undefined behavior plays a major role. Its implications were throughfully
> discussed by various works such as [@wang2012undefined, @d2015correctness,
> ```

This reference list doesn't seem to be formatted correctly, they might have to be listed individually (or there's some different syntax that I'm not aware of).
___
*[`book.md` line 1984 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVornBOCGiMnpW4rp1r:-NVornBOCGiMnpW4rp1s:b-sd22ec) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1984)):*
> ```Markdown
> The first example we will go through is a 15 years old vulnerability that
> affected the random number generator (RNG) in Mac OS X [@Wang2015]. At some
> point in the past, this vulnerability affected all *BSD operating systems, as
> ```

Nit: the star in `*BSD` should probably be escaped: `\*BSD`. I don't think this is causing any problems, but in the past I've had issues appear later in the text where I didn't expect it, because I didn't escape something earlier.
___
*[`book.md` line 1988 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVoZ_jhADHk_W-P3tp5:-NVoZ_jhADHk_W-P3tp6:b-o6zx7g) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1988)):*
> ```Markdown
> 
> In the random number generator of the system, more specifically in
> srandomdev(3), we can spot the following piece of code used in the seeding
> ```

Nit: you could use backticks to denote this as code here: \`srandomdev(3)\`. This would also look nice in a few more places below where you refer to function/macro names, compiler flags etc.
___
*[`book.md` line 1991 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVop8KK01qsoHEFU9Dk:-NVop8KK01qsoHEFU9Dl:bm559m5) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1991)):*
> ```Markdown
> logic:
> 
>       ``` {.c}
> ```

The formatting seem to go wrong here. Moving the backticks denoting the code blocks to the start of the line appears to fix this.  
___
*[`book.md` line 2032 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVojje1CF6Kch3wK9je:-NVojje1CF6Kch3wK9jf:b-ipq7ep) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2032)):*
> ```Markdown
> 
> In the shorter version of the generated assembly code, the compiler dropped the
> whole argument of `srandom` as an optimization. While this code respects the
> ```

"this code respects the standard" -> it might be clearer to say something like "this optimisation", or "the optimised code" instead.
___
*[`book.md` line 2036 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVok7Je1CGqoyYJdfng:-NVok7Je1CGqoyYJdfnh:bdvwhp0) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2036)):*
> ```Markdown
> of the RNG can now be predicted. 
> 
> In the meantime, this problem has be resovled in FreeBSD [@FbsdJunk], OpenBSD
> ```

Typo: resovled -> resolved.
___
*[`book.md` line 2040 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVousyCCVbFCzew4lBP:-NVousyCCVbFCzew4lBQ:b-vk7f5j) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2040)):*
> ```Markdown
> 
> Current solutions for detecting this class of vulnerabilities include LLVM's
> MemorySanitizer and Valgrind.
> ```

These tools are helpful for detecting the use of uninitialised data, which would be considered a problem to begin with, rather than the compiler optimisation, right? I think it would be useful to expand a bit more on the role of undefined behaviour at the start of the chapter, explaining, for example, how code that results in undefined behaviour can often work as the programmer expected until some optimisation is applied, and perhaps even talk a bit about why compilers rely on the absence of undefined behaviour in ways that appear aggressive in some occasions. (Of course, feel free to add a TODO for this instead!)
___
*[`book.md` line 2074 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVokotrAcg8yPUuk0zK:-NVokotrAcg8yPUuk0zL:b-ckqtip) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2074)):*
> ```Markdown
> 
> Linux was not the only project that suffered from this problem. Chromium
> [@ChromiumIssue] and Mozilla [@MozillaIssue] had problems in the past with this
> ```

Nit: Missing punctuation at the end of the sentence, or incomplete sentence?
___
*[`book.md` line 2106 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVol5At-6SuNpXrphC_:-NVol5At-6SuNpXrphCa:bg6dpgl) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2106)):*
> ```Markdown
> also tries to eliminate the risk of DSO by using the OPTIMIZER_HIDE_VAR macro.
> This, however, is not enough to fully eliminate dead stores [@MemZeroBarrier].
> In case of using LTO, the buffer `s` from is still vulnerable. For this reason,
> ```

Nit: "from" is unnecessary in this sentence?
___
*[`book.md` line 2126 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVosOSs9HCEmKWl2BSV:-NVosOSs9HCEmKWl2BSW:b-m7pl2j) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2126)):*
> ```Markdown
> 
>       ``` {.c}
>       + #define barrier_data(ptr) __asm__ __volatile__("": :"r"(ptr) :"memory")
> ```

This line is a little too long and it appears to be truncated in the html version.

**Review by kbeyls — COMMENTED** [review]
This looks amazing. Thank you so much @lucic71 for writing this.
I've only add a few nitpicks - feel free to disagree and ignore them.

One other item to still include in this patch is to add a copyright line for your contribution. We're trying to keep copyright information up to date. You can do so by adding a line near the very top of the book.md file. It currently looks like this.

```
SPDX-License-Identifier: CC-BY-4.0
copyright:
  - SPDX-FileCopyrightText: Copyright 2021-2022 Arm Limited <open-source-office@arm.com>
  - SPDX-FileCopyrightText: Copyright 2023 Bill Wendling <morbo@google.com>
```

If you own the copyright yourself (I assume that is most likely the case), the copyright line would probably looks somewhat as follows:

```
 - SPDX-FileCopyrightText: Copyright 2023 Lucian Popescu <>
```
with an email address or other way to contact you that you are happy to have published.

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-:-NVsWfi05V5TYQQcTnXN:bs0isxg)* status: 0 of 2 files reviewed, 22 unresolved discussions (waiting on @Dusilent, @g-kouv, @lucic71, and @Wang)

___
*[`book.md` line 1967 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsRWZL5O5Yb4g4r3lQ:-NVsRWZL5O5Yb4g4r3lR:bwl6quw) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1967)):*
> ```Markdown
> 
> Security vulnerabilities introduced by compilers have a long history.  Thompson
> [@Thompson1984] provides one of the oldest and most popular example in this
> ```

I'm wondering, should s/example/examples/ in this sentence, because it has the phrase "one of"?
___
*[`book.md` line 1974 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsSOVc9bF0GptACWdp:-NVsSOVc9bF0GptACWdq:btclxl8) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1974)):*
> ```Markdown
> 
> When discussing about compiler introduced security vulnerabilities,
> undefined behavior plays a major role. Its implications were throughfully
> ```

maybe s/throughfully/thoroughly/?
___
*[`book.md` line 1975 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVoj9VB27WeiklDosLN:-NVsSH8P4d4IpxZKmiPi:b-apwr1u) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1975)):*
<details><summary><i>Previously, g-kouv (Georgia Kouveli) wrote…</i></summary><blockquote>

This reference list doesn't seem to be formatted correctly, they might have to be listed individually (or there's some different syntax that I'm not aware of).
</blockquote></details>

Yeah, I think this needs to be spelled [@wang...][@d2015...][@dusilent...]
___
*[`book.md` line 1979 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsSkZP7augS00QLaXJ:-NVsSkZP7augS00QLaXK:b-60tj6j) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1979)):*
> ```Markdown
> projects that went through careful testing, such as Linux, FreeBSD or
> PostgreSQL, could not escape from this class of vulnerabilities. To better
> understand them, this chapter will contain several examples of such
> ```

I think it's ever so slightly easier to read "this chapter contains several examples" rather than "this chapter will contain several examples". Absolutely feel free to disagree and ignore this remark though!
___
*[`book.md` line 1982 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsT5td2yGGdLRdD3rN:-NVsT5td2yGGdLRdD3rO:bzgog8x) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1982)):*
> ```Markdown
> vulnerabilities, their implications and how they got fixed.
> 
> The first example we will go through is a 15 years old vulnerability that
> ```

As a rule of thumb, in the writing for this book, we're trying to keep sentence short. Presumably because the main authors so far have a tendency of writing long sentences ;) And shorter sentences are typically a bit easier to read.
With that in mind, I think "we will go through", can be removed from this sentence.
___
*[`book.md` line 1988 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsTcaP3gM3hyvC5fv_:-NVsTcaQ7djA3IzAAM4W:bkh4n13) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L1988)):*
> ```Markdown
> 
> In the random number generator of the system, more specifically in
> srandomdev(3), we can spot the following piece of code used in the seeding
> ```

I'm wondering is srandomdev should be in a monospace font as it refers to code? I'm not sure though...
___
*[`book.md` line 2036 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsUGfyEuTIOKz58XVH:-NVsUGfyEuTIOKz58XVI:b6rnz) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2036)):*
> ```Markdown
> of the RNG can now be predicted. 
> 
> In the meantime, this problem has be resovled in FreeBSD [@FbsdJunk], OpenBSD
> ```

also "has been resolved" rather than "has be resolved"?
___
*[`book.md` line 2036 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsURWMDeBDu6YJwLJt:-NVsURWMDeBDu6YJwLJu:ba7soyy) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2036)):*
> ```Markdown
> of the RNG can now be predicted. 
> 
> In the meantime, this problem has be resovled in FreeBSD [@FbsdJunk], OpenBSD
> ```

Maybe also say "FreeBSD and OpenBSD" rather than "FreeBSD, OpenBSD"?
___
*[`book.md` line 2080 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsUxBM7-I6mWc2Q2jn:-NVsUxBM7-I6mWc2Q2jo:b7ynrz6) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2080)):*
> ```Markdown
> taken from the Linux kernel. Because the compiler sees that the pointer hash is
> never used after this point, it decides to delete the memset operation. We call
> this dead store optimization (DSO). This has serious security implications
> ```

I think it would be good to add "dead store optimization" to the index. You can do so by writing \index{dead store elimination} at the end of the sentence. So far, the index only shows up in the PDF version of the book, not the HTML version.
___
*[`book.md` line 2103 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsVGZi723elpi40eKX:-NVsVGZj2YnXRWrawPup:b-bzx159) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2103)):*
> ```Markdown
>       ```
> 
> It still uses _memset_ to delete the associated security sensitive data, but it
> ```

I think it should be `memset` rather than _memset_ ?
___
*[`book.md` line 2103 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsWI-K8EEcXhnlVpbl:-NVsWI-K8EEcXhnlVpbm:bday6im) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2103)):*
> ```Markdown
>       ```
> 
> It still uses _memset_ to delete the associated security sensitive data, but it
> ```

I think adding memset to the index also makes sense here, i.e. adding \index{memset}
___
*[`book.md` line 2145 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-NVsW0k52a1o5Dt7fT2a:-NVsW0k52a1o5Dt7fT2b:b-r765i7) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/e5e8c0fd0db201362ac87961a6c3559f759ea2a0/book.md#L2145)):*
> ```Markdown
> forced to dereference the pointer to get to the actual `memset`, thus
> eliminating the risk of optimizing it out.
> ```

I think it would also be worthwhile to refer to the next funtion `memset_explicit` in C23 to help solve this issue. See https://en.cppreference.com/w/c/string/byte/memset and https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2897.htm for more details.

**Comment by kbeyls** [comment]
@all-contributors please add @lucic71 for code, content.

**Comment by lucic71** [comment]
I addressed all the feedback you left, I also created #202 to explain better the implications of UB in the beginning of the chapter.

**Review by kbeyls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200)* status: all files reviewed, 5 unresolved discussions (waiting on @Dusilent, @g-kouv, @lucic71, and @Wang)

**Review by g-kouv — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200#-:-NW1omAa0pfSSsy-ebdP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lucic71)

**Comment by g-kouv** [comment]
@lucic71 let me know if you can't merge because of permissions and I can do it for you (I'd do it now, but I'd prefer you to show as the committer if possible. You should remain the author of the commit either way).

**Comment by lucic71** [comment]
@g-kouv I can't merge but it's ok for me if you do the merging.

**Pull request merged**
