### PR TITLE
Format todos

### PR DESCRIPTION
**Pull request by kbeyls**
These 2 commits:
- make todo's formatted in the HTML output.
- simplify how we mark todo's, by using standard pandoc markdown syntax instead of something custom + getting rid of \missingcontent.

- - -
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/154)

### CODE REVIEW

**Review by kbeyls — COMMENTED** [review]
Two screenshots showing before and after:

### before:


### after:


> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/154#-:-NOPXEXd6pkUoqAaMBmF:b-ksvk1w)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @g-kouv and @JLouisKaplan-Arm)

**Review by JLouisKaplan-Arm — APPROVED** [review]
Looks great!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/154#-:-NOQX2OB17uoFQT0_7k9:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @g-kouv)

**Review by g-kouv — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/154#-:-NOioaYv8AMf_DiWy7mL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kbeyls)

**Review by kbeyls — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kbeyls)

**Pull request merged**
