### PR TITLE
[HTML] Add a "report issue" button.

### PR DESCRIPTION
**Pull request by kbeyls**
I hope this will make it easier for readers to report issues they see in the content of the book. I hope it will also make it more likely for readers to report the issues they see.

- - -
This change is [Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/146)

### CODE REVIEW

**Review by kbeyls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/146#-:-NN6dCIv3S00gjrfegz5:btoi9ek)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @g-kouv and @JLouisKaplan-Arm)

**Review by JLouisKaplan-Arm — APPROVED** [review]
The change itself looks good to me, though I can't decide if it's excessive to have both a GitHub and a 'report issue' button?

In favour of having it - not everyone is familiary with GitHub UI so it will be more intuitive.

Happy either way, let's see what @g-kouv thinks

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/146#-:-NN8vGBO-8DXfmKyA5Oy:bfn2930)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @g-kouv)

**Comment by kbeyls** [comment]
> The change itself looks good to me, though I can't decide if it's excessive to have both a GitHub and a 'report issue' button?
> 
> In favour of having it - not everyone is familiary with GitHub UI so it will be more intuitive.

Adding this would result in having 3 github-related buttons: "go to repo", "suggest an edit" and "report an issue".
We could make this one "github" dropdown button, with the 3 actions in the dropdown.
However, I'm wondering if "hiding" the "report an issue" in a dropdown would result in a reader being slightly less likely to discover that there is an easy way to report an issue... If only I knew more about UX design...
An example of a project using a "github dropdown" is https://jupyterbook.org/en/stable/intro.html.

I'm also thinking that if there was a nice way to have a "report an issue/suggest an improvement" next to the text, that might be useful too. For example, what if we had the button appear in the sidenote area, once per section? I guess that would probably be too much. But maybe have it appear next to the "get link" when you hover over a section title might be an OK balance?

**Review by g-kouv — APPROVED** [review]
I'm also in favour of having the button, happy to keep it as it is and revisit later if we want to change it to a dropdown.

> I'm also thinking that if there was a nice way to have a "report an issue/suggest an improvement" next to the text, that might be useful too. For example, what if we had the button appear in the sidenote area, once per section? I guess that would probably be too much. But maybe have it appear next to the "get link" when you hover over a section title might be an OK balance?

I don't think I'd need/use additional buttons, since the existing buttons stay anchored when scrolling through the text, so I'm happy for this change to go in as-is! If we split the content into multiple files, individual "suggest an improvement" buttons might be more important.


:lgtm:

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/146#-:-NNGcP909nVvm3xoM9b6:b-ef1xd8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kbeyls)

**Pull request merged**
